spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacos
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    data: data.sql

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

    database: mysql

  data:
    elasticsearch:
      repositories:
        enabled: true

server:
  port: 9090