server:
  port: 8080
#  ssl:
#    key-store: file:///path:to/mykeys.jks
#    key-store-password: letmein
#    key-password: letmein

spring:

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create

    database: mysql

    data:
      elasticsearch:
        repositories:
          enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/tacos
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #    data: data.sql

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    tacos: WARN
    root: WARN
    org.springframework.security: DEBUG
  path: /var/logs/
  file: TacoCloud.log

greeting:
  welcome: Вы используете ${spring.application.name}

taco:
  orders:
    pageSize: 10